version: '3.8'

services:
  ags-mcp-server:
    image: ags-mcp-server:complete
    container_name: ags-mcp-complete
    volumes:
      # Mount your AGS game rooms directory
      - ./demo:/app/rooms:rw
      # Mount any additional game files
      - ./games:/app/games:ro
    environment:
      - NODE_ENV=production
      - MCP_SERVER_PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "crmpak", "--help"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - ags-network

  # Optional: Add a file server for easy room file management
  file-server:
    image: halverneus/static-file-server:latest
    container_name: ags-file-server
    ports:
      - "8080:8080"
    volumes:
      - ./demo:/web:ro
      - ./games:/web/games:ro
    environment:
      - FOLDER=/web
      - PORT=8080
    networks:
      - ags-network

networks:
  ags-network:
    driver: bridge